// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/lottery/bet_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BetInfo struct {
	BetId int64 `protobuf:"varint,1,opt,name=betId,proto3" json:"betId,omitempty"`
}

func (m *BetInfo) Reset()         { *m = BetInfo{} }
func (m *BetInfo) String() string { return proto.CompactTextString(m) }
func (*BetInfo) ProtoMessage()    {}
func (*BetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d761a3374fc68543, []int{0}
}
func (m *BetInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BetInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetInfo.Merge(m, src)
}
func (m *BetInfo) XXX_Size() int {
	return m.Size()
}
func (m *BetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BetInfo proto.InternalMessageInfo

func (m *BetInfo) GetBetId() int64 {
	if m != nil {
		return m.BetId
	}
	return 0
}

func init() {
	proto.RegisterType((*BetInfo)(nil), "naruto0913.lottery.lottery.BetInfo")
}

func init() { proto.RegisterFile("lottery/lottery/bet_info.proto", fileDescriptor_d761a3374fc68543) }

var fileDescriptor_d761a3374fc68543 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xc9, 0x2f, 0x29,
	0x49, 0x2d, 0xaa, 0xd4, 0x87, 0xd1, 0x49, 0xa9, 0x25, 0xf1, 0x99, 0x79, 0x69, 0xf9, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0x52, 0x79, 0x89, 0x45, 0xa5, 0x25, 0xf9, 0x06, 0x96, 0x86, 0xc6,
	0x7a, 0x50, 0x25, 0x30, 0x5a, 0x49, 0x9e, 0x8b, 0xdd, 0x29, 0xb5, 0xc4, 0x33, 0x2f, 0x2d, 0x5f,
	0x48, 0x84, 0x8b, 0x35, 0x29, 0xb5, 0xc4, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x08,
	0xc2, 0x71, 0x72, 0x3f, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18,
	0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xdd, 0xf4,
	0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x84, 0x0d, 0x70, 0x47, 0x54, 0xc0,
	0x59, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0x60, 0xc7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xff, 0x5d, 0xe5, 0xbe, 0xae, 0x00, 0x00, 0x00,
}

func (m *BetInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BetInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BetInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BetId != 0 {
		i = encodeVarintBetInfo(dAtA, i, uint64(m.BetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBetInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovBetInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BetInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BetId != 0 {
		n += 1 + sovBetInfo(uint64(m.BetId))
	}
	return n
}

func sovBetInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBetInfo(x uint64) (n int) {
	return sovBetInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BetInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBetInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BetInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BetInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetId", wireType)
			}
			m.BetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBetInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBetInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBetInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBetInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBetInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBetInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBetInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBetInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBetInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBetInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBetInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBetInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBetInfo = fmt.Errorf("proto: unexpected end of group")
)
