// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/lottery/event.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DoBet struct {
	LotteryID int64  `protobuf:"varint,1,opt,name=lotteryID,proto3" json:"lotteryID,omitempty"`
	BetID     int64  `protobuf:"varint,2,opt,name=betID,proto3" json:"betID,omitempty"`
	UserAddr  string `protobuf:"bytes,3,opt,name=userAddr,proto3" json:"userAddr,omitempty"`
	BetAmount int64  `protobuf:"varint,4,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
}

func (m *DoBet) Reset()         { *m = DoBet{} }
func (m *DoBet) String() string { return proto.CompactTextString(m) }
func (*DoBet) ProtoMessage()    {}
func (*DoBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_85234cf93f0f7904, []int{0}
}
func (m *DoBet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DoBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DoBet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DoBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoBet.Merge(m, src)
}
func (m *DoBet) XXX_Size() int {
	return m.Size()
}
func (m *DoBet) XXX_DiscardUnknown() {
	xxx_messageInfo_DoBet.DiscardUnknown(m)
}

var xxx_messageInfo_DoBet proto.InternalMessageInfo

func (m *DoBet) GetLotteryID() int64 {
	if m != nil {
		return m.LotteryID
	}
	return 0
}

func (m *DoBet) GetBetID() int64 {
	if m != nil {
		return m.BetID
	}
	return 0
}

func (m *DoBet) GetUserAddr() string {
	if m != nil {
		return m.UserAddr
	}
	return ""
}

func (m *DoBet) GetBetAmount() int64 {
	if m != nil {
		return m.BetAmount
	}
	return 0
}

type FinishLottery struct {
	LotteryID int64  `protobuf:"varint,1,opt,name=lotteryID,proto3" json:"lotteryID,omitempty"`
	WinnerInd int64  `protobuf:"varint,2,opt,name=winnerInd,proto3" json:"winnerInd,omitempty"`
	Winner    string `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (m *FinishLottery) Reset()         { *m = FinishLottery{} }
func (m *FinishLottery) String() string { return proto.CompactTextString(m) }
func (*FinishLottery) ProtoMessage()    {}
func (*FinishLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_85234cf93f0f7904, []int{1}
}
func (m *FinishLottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FinishLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FinishLottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FinishLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishLottery.Merge(m, src)
}
func (m *FinishLottery) XXX_Size() int {
	return m.Size()
}
func (m *FinishLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishLottery.DiscardUnknown(m)
}

var xxx_messageInfo_FinishLottery proto.InternalMessageInfo

func (m *FinishLottery) GetLotteryID() int64 {
	if m != nil {
		return m.LotteryID
	}
	return 0
}

func (m *FinishLottery) GetWinnerInd() int64 {
	if m != nil {
		return m.WinnerInd
	}
	return 0
}

func (m *FinishLottery) GetWinner() string {
	if m != nil {
		return m.Winner
	}
	return ""
}

func init() {
	proto.RegisterType((*DoBet)(nil), "naruto0913.lottery.lottery.DoBet")
	proto.RegisterType((*FinishLottery)(nil), "naruto0913.lottery.lottery.FinishLottery")
}

func init() { proto.RegisterFile("lottery/lottery/event.proto", fileDescriptor_85234cf93f0f7904) }

var fileDescriptor_85234cf93f0f7904 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xc9, 0x2f, 0x29,
	0x49, 0x2d, 0xaa, 0xd4, 0x87, 0xd1, 0xa9, 0x65, 0xa9, 0x79, 0x25, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x52, 0x79, 0x89, 0x45, 0xa5, 0x25, 0xf9, 0x06, 0x96, 0x86, 0xc6, 0x7a, 0x50, 0x79,
	0x18, 0xad, 0x54, 0xca, 0xc5, 0xea, 0x92, 0xef, 0x94, 0x5a, 0x22, 0x24, 0xc3, 0xc5, 0x09, 0x15,
	0xf3, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x08, 0x08, 0x89, 0x70, 0xb1, 0x26,
	0xa5, 0x96, 0x78, 0xba, 0x48, 0x30, 0x81, 0x65, 0x20, 0x1c, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2,
	0xd4, 0x22, 0xc7, 0x94, 0x94, 0x22, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x64,
	0x5e, 0x52, 0x6a, 0x89, 0x63, 0x6e, 0x7e, 0x69, 0x5e, 0x89, 0x04, 0x0b, 0xc4, 0x3c, 0xb8, 0x80,
	0x52, 0x32, 0x17, 0xaf, 0x5b, 0x66, 0x5e, 0x66, 0x71, 0x86, 0x0f, 0xc4, 0x0a, 0x02, 0xd6, 0xcb,
	0x70, 0x71, 0x96, 0x67, 0xe6, 0xe5, 0xa5, 0x16, 0x79, 0xe6, 0xa5, 0x40, 0x9d, 0x80, 0x10, 0x10,
	0x12, 0xe3, 0x62, 0x83, 0x70, 0xa0, 0x8e, 0x80, 0xf2, 0x9c, 0xdc, 0x4f, 0x3c, 0x92, 0x63, 0xbc,
	0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63,
	0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x37, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f,
	0x57, 0x1f, 0x11, 0x38, 0xf0, 0xc0, 0xab, 0x80, 0xb3, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8,
	0xc0, 0xe1, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x1e, 0xad, 0x10, 0x66, 0x01, 0x00,
	0x00,
}

func (m *DoBet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DoBet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DoBet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BetAmount != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BetAmount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.UserAddr) > 0 {
		i -= len(m.UserAddr)
		copy(dAtA[i:], m.UserAddr)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.UserAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BetID != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BetID))
		i--
		dAtA[i] = 0x10
	}
	if m.LotteryID != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.LotteryID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FinishLottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FinishLottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FinishLottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Winner) > 0 {
		i -= len(m.Winner)
		copy(dAtA[i:], m.Winner)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Winner)))
		i--
		dAtA[i] = 0x1a
	}
	if m.WinnerInd != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.WinnerInd))
		i--
		dAtA[i] = 0x10
	}
	if m.LotteryID != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.LotteryID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DoBet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LotteryID != 0 {
		n += 1 + sovEvent(uint64(m.LotteryID))
	}
	if m.BetID != 0 {
		n += 1 + sovEvent(uint64(m.BetID))
	}
	l = len(m.UserAddr)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BetAmount != 0 {
		n += 1 + sovEvent(uint64(m.BetAmount))
	}
	return n
}

func (m *FinishLottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LotteryID != 0 {
		n += 1 + sovEvent(uint64(m.LotteryID))
	}
	if m.WinnerInd != 0 {
		n += 1 + sovEvent(uint64(m.WinnerInd))
	}
	l = len(m.Winner)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DoBet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DoBet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DoBet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryID", wireType)
			}
			m.LotteryID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LotteryID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetID", wireType)
			}
			m.BetID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetAmount", wireType)
			}
			m.BetAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FinishLottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FinishLottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FinishLottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryID", wireType)
			}
			m.LotteryID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LotteryID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinnerInd", wireType)
			}
			m.WinnerInd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WinnerInd |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Winner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Winner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
